protocol=sql
host=0.0.0.0
port=4334
alt-host=transactor

sql-url=jdbc:postgresql://postgres:5432/datomic
sql-user=datomic
sql-password=datomic
sql-driver-class=org.postgresql.Driver

license-key=${DATOMIC_LICENSE_KEY}

memory-index-threshold=32m
memory-index-max=512m
object-cache-max=512m

storage-access=remote
encrypt-channel=false

write-concurrency=4
read-concurrency=8

data-dir=/opt/datomic/data
log-dir=/opt/datomic/log
